### PR TITLE
Use gvt to vendor dependencies

### PR DESCRIPTION
**Pull request by pcf-core-services**
[#130791609]

Signed-off-by: Urvashi Reddy ureddy@pivotal.io

### CODE REVIEW

**Comment by njbennett** [comment]
Is there an update to this?

We'd like to update away from our own fork of the route-registrar

**Comment by shalako** [comment]
The PR came with no description. What does this do and why is it valuable?

**Comment by chendrix** [comment]
We had a conversation with the routing team about this when this PR was made.

The Core Services team needs per-instance routing (proxy-0-p-mysql.domain -> IP 1, proxy-1-p-mysql.domain -> IP 2). This is not supported by routing-release out of the box, so instead we write our own "routing errand" using route-registrar the package.

We have an old version of route-registrar we've submoduled in to cf-mysql-release, and we needed to update it. However, we cannot update it because it doesn't vendor its own dependencies, and would require us to add a bunch of extraneous submodules to cf-mysql-release, mimicking the mono-repo of routing-release.

This PR adds that needed vendoring to route-registrar.

Why is it valuable? We believe strongly that binaries should be buildable without the rest of one's mono-repo.

**Comment by shalako** [comment]
prioritizing for eng team review.

**Comment by shashwathi** [comment]
Hi @robdimsdale,

We are inclining towards not vendoring for route-registrar module. To solve the per-instance routing problem we think surgical routing(very fancy name for instance routing!) would be a better and cleaner solution. 

For better understanding of surgical routing, consider an example of mysql deployment which is configured with n proxy's. `route registrar` job on each proxy would register route `proxy.external-host` with its own IP and port. Gorouter now supports instance routing with header ` X-Cf-App-Instance`. To target a given instance of proxy we could run `curl -H "X-Cf-App-Instance: app_id:app_index" proxy.external-host`. 

Missing feature: Route registrar job does not support adding application ID and index. This should be a fairly simple change and routing team is willing to do that work( or we could pair on it too if you prefer). 

I wanted to know your input on this approach instead of vendoring. 
 
Regards
Shash
CF Routing team

**Comment by shalako** [comment]
Sorry, we didn't consider the obvious issue with using a header for this. I should have realized that wouldn't work.

@robdimsdale Here's an alternative: we could enhance route-registrar to support configuration of the backend IP for a route, as an override to the auto-detect behavior. The mysql team could then use the mainline route-registrar, and configure it on the switchboard to register the routes for all instances. 

If one instance of Switchboard fails currently, you'll get a 404 because the route will be pruned. With the new route-registrar, you'll get a 502 because other instances are still registering all the routes. 

This makes me somewhat uncomfortable, because it seems like an anti-pattern. An instance of a job probably shouldn't register routes for another instance when it shouldn't have to know the health of the other instance. On the other hand, I have wondered if the route emitters could dog food route-registrar...

**Comment by robdimsdale** [comment]
@shalako interesting. We hadn't considered having all instances registering all routes for other instances.

It should work fine from a technical perspective, and in some ways the product impact might be preferable - returning a 502 means you know the backend should be there but isn't healthy, whereas a 404 doesn't tell you if the route is meant to be available or not. For system components which do not dynamically scale this might be an advantage.

I'll let @menicosia weigh in on the product impact of this feature, but from an engineering perspective this appears to allow us to colocate the routing release with cf-mysql-release and stop maintaining our own fork. It also means we could close this PR as we wouldn't have any visibility into how/why the routing release components vendor their dependencies.

**Comment by menicosia** [comment]
Product says +1!

-- 
--<br> Marco Nicosia<br> Product Manager, Cloud Foundry MySQL<br> Pivotal,
Inc.<br>

**Comment by abbyachau** [comment]
Hi @robdimsdale and @menicosia, here is the link to the tracker story for the alternate solution we've proposed above: https://www.pivotaltracker.com/story/show/135363119. If you have any comments, please leave them in that story. We're going to close this PR now. Thank you!

**Pull request closed without merging**
